import { stub, tag } from "./setup.ts";
import assert from "node:assert/strict";
import http from "node:http";
import { after, test } from "node:test";
import { config } from "@aihot/backend/config";
import { sql, closeDb } from "@aihot/backend/db";
import { stopBoss } from "@aihot/backend/jobs/queue";
import { collectSource, adaptIntervals } from "@aihot/backend/sources/collect";
import { fromHtml } from "@aihot/backend/sources/web-list";
import { normalizeMncCandidate } from "@aihot/backend/sources/mnc";
import { collectFindings } from "@aihot/backend/operations/alerts";
import type { SourceRow } from "@aihot/backend/sources/types";
import seeds from "../industry/sources.json" with {type:"json"};
import { unsupportedConfig } from "@aihot/backend/sources/config-keys";
let broken = false;
const now = new Date().toISOString();
const server = http.createServer((_req,res)=>{
  res.setHeader("content-type","text/html");
  res.end(broken ? '<html>Changed layout</html>' : `<article><a href="https://www.novartis.com/news/media-releases/test-${T}"><h3>Phase III clinical update</h3></a><time datetime="${now}"></time></article>`);
});
const T=tag(), id=`mnc-test-${T}`;
await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));
const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
config.allowPrivateNetworkFetch=true;
const settings={url,itemSelector:'article',titleSelector:'h3',publishedAtSelector:'time',_mnc:{company:'Novartis',ticker:'NVS',category:'ad_hoc'},_aihot:{fixedIntervalMinutes:15,initialBackfillMonths:1}};
after(async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));await stopBoss();await closeDb();});
test('AstraZeneca media cards retain the title and date without unrelated links',()=>{
  const seed=seeds.sources.find(s=>s.id==='mnc-astrazeneca')!;
  const source={...seed,cursor:null,fail_count:0} as SourceRow;
  const items=fromHtml('<a href="/about">About</a><li class="dynamic-news-container__item"><a href="/media-centre/press-releases/2026/trial.html"><div class="dynamic-news-container__item-title">Phase III trial results</div><time datetime="2026-09-28">28 September 2026</time></a></li>',String(seed.config.url),source);
  assert.equal(items.length,1);
  assert.equal(items[0]!.title,'Phase III trial results');
  assert.equal(items[0]!.publishedAt?.toISOString(),'2026-09-28T00:00:00.000Z');
});
test('MNC config is supported; Novartis tabs stay separate and metadata keeps original timezone',()=>{
  for(const s of seeds.sources)assert.deepEqual(unsupportedConfig(s.kind as SourceRow['kind'],s.config),[]);
  const source={...seeds.sources[6],cursor:null,fail_count:0,config:{...settings,itemSelector:'#tab-ad-hoc-releases article'}} as SourceRow;
  const html='<div id="tab-press-releases"><article><a href="/ordinary">Ordinary</a></article></div><div id="tab-ad-hoc-releases"><article><a href="/news/media-releases/trial?utm_source=x"><h3>Trial results</h3></a><time datetime="2026-09-08T09:00:00+02:00"></time></article></div>';
  const items=fromHtml(html,'https://www.novartis.com/news',source);
  assert.equal(items.length,1);
  const row=normalizeMncCandidate(items[0]!,source).raw as {mnc:{published_at:string;published_at_utc:string;dedup_key:string}};
  assert.equal(row.mnc.published_at,'2026-09-08T09:00:00+02:00');
  assert.equal(row.mnc.published_at_utc,'2026-09-08T07:00:00.000Z');
  assert.equal(row.mnc.dedup_key,(normalizeMncCandidate({...items[0]!,url:items[0]!.url.replace('?utm_source=x','')},source).raw as typeof row).mnc.dedup_key);
});
test('second collection creates zero records, fixed rate survives adaptation, two broken parses alert',async()=>{
  await sql`INSERT INTO sources(id,name,kind,config,tier,participation_mode,interval_minutes) VALUES(${id},'MNC fixture','web_list',${sql.json(settings)},'T1','editorial',15)`;
  assert.equal((await collectSource(id)).created,1);
  assert.equal((await collectSource(id)).created,0);
  await adaptIntervals();
  assert.equal((await sql`SELECT interval_minutes FROM sources WHERE id=${id}`)[0]!.interval_minutes,15);
  broken=true;
  assert.equal((await collectSource(id)).status,'failed');
  assert.equal((await collectSource(id)).status,'failed');
  const row=(await sql`SELECT fail_count,health FROM sources WHERE id=${id}`)[0]!;
  assert.equal(row.fail_count,2);assert.equal(row.health,'failing');
  assert.ok((await collectFindings()).some(f=>f.key===`mnc.source.${id}`));
  broken=false;
  assert.equal((await collectSource(id)).status,'ok');
  assert.ok(!(await collectFindings()).some(f=>f.key===`mnc.source.${id}`));
});
